
# Manifest file for the Application
manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
  defaults:
    remote: zephyrproject-rtos
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.7.1
      path: zephyr
      
    - name: hal_stm32
      revision: d5fb525486544f7fcec365a89c2ca5ea936618f5
      path: modules/hal/stm32
      groups:
        - hal
      
    - name: hal_nxp
      revision: cae40020064894f67b00215dad2baf7c743e1dfb
      path: modules/hal/nxp
      groups:
        - hal
    # Add other projects/modules as needed, e.g., MCUBoot:
    # - name: mcuboot
    #   revision: v1.9.0
    #   path: modules/lib/mcuboot
  self:
    path: app  # Or wherever your manifest repository is located